#!/bin/bash

if [ "$(pwd)" != "$(cd "$(dirname "${BASH_SOURCE}")"; pwd)" ]; then
  echo 'play_icfp2015 command cannot be run outside of the directory.' >&2
  exit 1
fi
php "$(dirname "${BASH_SOURCE}")/play_icfp2015.php" "$@"
