cc_binary(
    name = "controller",
    srcs = ["controller.cc"],
    deps = [
        "//base",
    ],
)

cc_binary(
    name = "worker",
    srcs = ["worker.cc"],
    deps = [
        "//base",
        "//boost",
    ],
)
