licenses(["notice"])

package(default_visibility = ["//visibility:public"])

java_binary(
    name = "wata",
    srcs = glob(["**/*.java"]),
    main_class = "Main",
    deps = [
        "//src/gson",
    ],
)
