licenses(["notice"])

package(default_visibility = ["//visibility:public"])

cc_library(
    name = "gflags",
    srcs = [
        "config.h",
        "gflags_completions.h",
        "gflags_declare.h",
        "gflags_gflags.h",
        "gflags.h",
        "gflags_completions.cc",
        "gflags_reporting.cc",
        "gflags.cc",
        "mutex.h",
        "util.h",
    ],
)
